/**
 * Builds dist/cu-agent.js: one minified IIFE (es2018, so older Chromium runs it) that installs
 * `window.__cuAgent`, plus a source map and dist/cu-agent.d.ts for script-tag consumers.
 *
 * Run directly (`node build.mjs`, `npm run build`), or let `agentSource()` in src/index.ts run it
 * on demand when dist/ is missing or older than src/. esbuild resolves from the repo root.
 */
import { build } from 'esbuild';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const distDir = path.join(here, 'dist');

/** Absolute path of the built bundle. */
export const OUTFILE = path.join(distDir, 'cu-agent.js');

const DTS = `// Generated by build.mjs. Types for dist/cu-agent.js, which installs window.__cuAgent.
export type * from '../src/types.js';
`;

/** Builds the bundle, its source map and its type declarations into dist/. */
export async function buildAgent() {
  await mkdir(distDir, { recursive: true });
  await build({
    entryPoints: [path.join(here, 'src', 'entry.ts')],
    outfile: OUTFILE,
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2018',
    minify: true,
    sourcemap: true,
    legalComments: 'none',
    logLevel: 'warning',
  });
  await writeFile(path.join(distDir, 'cu-agent.d.ts'), DTS);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await buildAgent();
}
